from __future__ import annotations

from collections import defaultdict

from orphan_radar.core.models import ReviewQueueItem, RunSummary


def render_review_report(items: list[ReviewQueueItem], summary: RunSummary) -> str:
    lines = [
        '# Orphan Radar Review',
        '',
        f'Generated by Orphan Radar at `{summary.generated_at}`.',
        '',
        '**Source mutation status:** verified unchanged.',
        '',
        '## Summary',
        '',
        f'- Notes scanned: {summary.total_notes_scanned}',
        f'- Hard orphans: {summary.hard_orphans_found}',
        f'- Weak orphans: {summary.weak_orphans_found}',
        f'- Bridge candidates: {summary.bridge_candidates_found}',
        f'- Candidate edges: {summary.candidate_edges_generated}',
        '',
        'Confidence scores are heuristic ranking scores, not probabilities.',
        '',
    ]
    grouped: defaultdict[str, list[ReviewQueueItem]] = defaultdict(list)
    for item in items:
        grouped[item.track].append(item)

    headings = {
        'cleanup': 'Track 1 — Cleanup Queue: Hard Orphans',
        'structural_gap': 'Track 2 — Structural Gap Queue: Weak Orphans',
        'bridge': 'Track 3 — Bridge Candidates',
        'calibration': 'Track 4 — Calibration / Boundary Cases',
    }
    for track in ['cleanup', 'structural_gap', 'bridge', 'calibration']:
        if track not in grouped:
            continue
        lines.extend(['---', '', f'## {headings[track]}', ''])
        for idx, item in enumerate(grouped[track], 1):
            target = f' → **{item.target_title}**' if item.target_title else ''
            lines.extend([
                f'### {idx}. **{item.source_title}**{target}',
                '',
                f'- Priority score: `{item.priority_score:.3f}`',
                f'- Explanation: {item.explanation or "local evidence passed review threshold"}',
                '- Review:',
                '  - [ ] Accept',
                '  - [ ] Reject',
                '  - [ ] Needs better target',
                '',
            ])
            if item.target_title:
                lines.append(f'Suggested link: `[[{item.target_title}]]`')
                lines.append('')
    return '\n'.join(lines)
