from __future__ import annotations

from pathlib import Path
import re

from orphan_radar.core.models import NoteRecord
from orphan_radar.core.settings import RadarSettings
from orphan_radar.io.hasher import sha256_file
from orphan_radar.parse.links import extract_markdown_file_links, extract_wiki_links, normalize_title_key
from orphan_radar.parse.tags import extract_tags, parse_frontmatter
from orphan_radar.parse.tokens import tokenize

HEADING_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)


class SourceStore:
    def read_text(self, path: Path) -> str:
        return path.read_text(encoding='utf-8', errors='replace')

    def write_text(self, *args, **kwargs) -> None:  # pragma: no cover - safety guard
        raise RuntimeError('SourceStore is read-only')


def should_skip_path(path: Path, root: Path, settings: RadarSettings) -> bool:
    rel_parts = set(path.relative_to(root).parts[:-1])
    if rel_parts & settings.excluded_folders:
        return True
    return path.suffix.lower() not in {'.md', '.txt'}


def scan_source_files(source_dir: Path, settings: RadarSettings) -> list[Path]:
    source_dir = source_dir.resolve()
    paths: list[Path] = []
    for path in source_dir.rglob('*'):
        if path.is_file() and not should_skip_path(path, source_dir, settings):
            paths.append(path.resolve())
    return sorted(set(paths))


def title_from_content(path: Path, body: str, metadata: dict[str, str]) -> str:
    if metadata.get('title'):
        return metadata['title'].strip()
    match = HEADING_RE.search(body or '')
    if match:
        return match.group(1).strip()
    return path.stem


def is_generated_output(path: Path, metadata: dict[str, str], body: str) -> bool:
    name = path.name.lower()
    if 'orphan radar review' in name or metadata.get('generated_by') == 'orphan-radar':
        return True
    return 'Generated by Orphan Radar' in body[:500]


def parse_note(path: Path, source_dir: Path, settings: RadarSettings, store: SourceStore | None = None) -> NoteRecord:
    store = store or SourceStore()
    content = store.read_text(path)
    metadata, body = parse_frontmatter(content)
    title = title_from_content(path, body, metadata)
    tags = extract_tags(body, metadata)
    outbound_links = extract_wiki_links(body) | extract_markdown_file_links(body)
    title_tokens = tokenize(title, generic_terms=settings.generic_terms)
    content_tokens = tokenize(body, generic_terms=settings.generic_terms)
    relpath = str(path.resolve().relative_to(source_dir.resolve()))
    note_id = normalize_title_key(title)
    folder_path = str(Path(relpath).parent) if str(Path(relpath).parent) != '.' else ''
    search_text = f"{title}\n{' '.join(sorted(tags))}\n{body}"
    return NoteRecord(
        note_id=note_id,
        filepath=str(path.resolve()),
        relpath=relpath,
        title=title,
        content=body,
        search_text=search_text,
        file_hash=sha256_file(path),
        folder_path=folder_path,
        outbound_links=outbound_links,
        tags=tags,
        metadata=metadata,
        title_tokens=title_tokens,
        content_tokens=content_tokens,
        word_count=len(content_tokens),
        is_generated_output=is_generated_output(path, metadata, body),
    )


def load_notes(source_dir: Path, settings: RadarSettings) -> tuple[list[NoteRecord], list[Path]]:
    paths = scan_source_files(source_dir, settings)
    notes = [parse_note(path, source_dir, settings) for path in paths]
    return notes, paths
